### ISSUE TITLE
error gen~: expr: can only set as typed-in argument

### ISSUE THREAD

**Issue by macduff111** [gibber-cc/gibberwocky#19]
Hi
I'm trying out gibberwocky.live and it seems to work ok except for gen based modulation. I get:

error gen~: expr: can only set as typed-in argument

Saw someone else with the same problem on the cycling74 forum https://cycling74.com/forums/debugging-gibberwocky

Running Live 9.7.4 Max 8.0 and Chrome 71

Any ideas?

(Really like gibberwocky so far btw!)

**Comment by ode2glitches** [comment]
Hi!

Same problem here. I tried with "/beta", "/live" and "index.html" as note editors.

Running Live 10.1, Max 8.0, Chrome 79 and latest version of Gibberwocky. 

Didn't find any documentation for troubleshooting. Also Slack group invitation is revoked, I can not join the Slack group, for your information.

**Comment by grrrwaaa** [comment]
Hi there ode2glitches,

This was due to Gibberwocky using a feature of Max that was recently deprecated; we have found a fix that can work around the issue and should be able to get that into Gibberwocky soon. 

Graham

**Comment by charlieroberts** [comment]
@ode2glitches did you try using the version at gibberwocky.cc/burble?

Sorry this repo / the readme really needs some love right now; /burble is the most recent editor

**Comment by charlieroberts** [comment]
OK!!! Try this:

https://github.com/gibber-cc/gibberwocky/releases/tag/1.21

**Comment by ode2glitches** [comment]
Hi dear @grrrwaaa and @charlieroberts !

Thanks for your efforts, it's working well now :)

I got "gibberwocky.max was not able to connect." on the console but everything seems OK right now, Take care!

**Comment by charlieroberts** [comment]
great news!
