### ISSUE TITLE
using genish for modulation

### ISSUE THREAD

**Issue by magwa101** [gibber-cc/gibberwocky#9]
I am running Live 10, Max 8, 10.13.3, I just installed 1.2.
I'm testing gibberwocky.demo.
I get this, is it expected:
gibberwocky is ready to burble.
error Compiling Gen graphs is not authorized for this install of Max; using genish.js for modulation

BTW Just got on gibberwocky today, grabbed your 1.2 update right away. Great stuff.

**Comment by charlieroberts** [comment]
`using genish.js for modulation` is the important part of that message. It's saying it can't compile Gen but will calculate modulations in the browser instead. Are modulations working?

**Comment by magwa101** [comment]
Modulations are working. I'm testing through them and will have more details but they seem to be working well.
